[CREATE] Header and Modal
EntryDSM/poodle pull request #1
Opened 2020-04-02 15:53 UTC by woochanleee

# 제목을 적어주세요
Header와 Modal을 제작하여 PR을 날립니다.
## 목적
pr을 하는 목적 or 코드를 짠 목적..?
### 요약
기초적인 루트 리듀서와 루트 사가를 적용하고 헤더 컴포넌트와 모달 컴포넌트를 제작했다.
### 상세
Header에서 로그인 상태를 리덕스로 관리하여 로그인 여부 에 따른 화면을 보여준다.

Modal on/off를 리덕스로 관리하여 필요한 상황에 따라 dispatch(액션명)을 통해 모달을 관리한다.
## 영향을 미치는 부분
헤더 리듀서에서 로그인정보(토큰, 이름) 등을 관리하므로 관련된 정보가 필요한경우 여기서 사용해야한다.
## 참조(선택)
이슈가 뭔지 잘 모르겠네요!

2020-04-03 08:45 UTC, junu126 commented
지금 보면 추가된 라인 수가 1300개가 넘는데.. PR하나당 추천 라인수는 100에서 200줄 정도로 하면 좋을 것 같아요.. 이렇게 하면 너무 리뷰하는데 힘드러여 ㅠ

2020-04-03 14:11 UTC, woochanleee commented
> 지금 보면 추가된 라인 수가 1300개가 넘는데.. PR하나당 추천 라인수는 100에서 200줄 정도로 하면 좋을 것 같아요.. 이렇게 하면 너무 리뷰하는데 힘드러여 ㅠ

흐엑... 죄송합니다 다음 pr부턴 짧게 나눠서 보내겠습니다..

2020-04-05 08:16 UTC, junu126 commented on package.json
> +{
요론놈은 develop branch에서 커밋해줘연

2020-04-05 08:16 UTC, junu126 commented on poodle/src/components/common/Header/Header.tsx
> +import * as S from '../../../styles/common/Header';
절대 경로 사용해보는것도 나쁘지 않을 것 같네요

2020-04-05 08:17 UTC, junu126 commented on poodle/src/components/common/Header/Header.tsx
> +                            <S.GNB onClick={logout}>{user.userName}</S.GNB>
`GNB`가 뭐에요..?

2020-04-05 08:33 UTC, junu126 requested changes
전체적으로 Type이 없는 곳이 많네영..
그리고 완성하지 못한 코드를 commit했는데 이러지 말고 다 완성 시키고 해주십셔

2020-04-05 08:33 UTC, junu126 commented on poodle/src/components/common/Header/Header.tsx
> +function Header({ isLogin,  user, loginError, loginLoading, login, logout }: HeaderProps) {
react에서 ts를 사용할 때 함수형으로 작성하고 있다면 컴포넌트의 `return type`을 달아줘야해요.

```
import React, { FC } from 'react';
```

`FC`는 `functional component` 의 약자로 함수형 컴포넌트의 return type을 나타냅니다.

```
function Header({ ... }: HeaderProps): FC { ... }
```

이런 느낌으로 사용하시면 되여

2020-04-05 08:33 UTC, junu126 commented on poodle/src/components/common/Modal/LoginModal/LoginModal.tsx
> +            <S.ETCSentence onClick={() => dispatch(modalOn(WARNINGMODAL))}>
`useCallback`을 이용해서 함수를 따로 빼주세요. 이렇게 하면 컴포넌트 render 할 때마다 함수를 새로 만듭니다.

2020-04-05 08:33 UTC, junu126 commented on poodle/src/components/common/Modal/ModalContent.tsx
> +ModalContent.defaultProps = {
?? 이거 왜 적은거에요? TS사용하는데

2020-04-05 08:33 UTC, junu126 commented on poodle/src/components/common/Modal/ModalContent.tsx
> +    const onClick = useCallback(() => {
함수명..? 명시적으로 바꿔주시고 해당 함수가 있는 이유가 뭔가요..?

onClick2도 마찬가지고

2020-04-05 08:33 UTC, junu126 commented on poodle/src/components/common/Modal/ModalContent.tsx
> +const imageList: any = {
`enum` 찾아보세요

```
enum IMAGE_LIST {
    BlueSuccess = 'BlueSuccess',
    BlueCheck = 'BlueCheck',
}
```

이런 느낌으로 사용할 수 있습니다

2020-04-05 08:33 UTC, junu126 commented on poodle/src/components/common/Modal/ResetModal/ResetModal.tsx
> +    const pageList = [
constance 파일 하나 만들어서 따로 빼주세요. 그리고 type 달아주고

2020-04-05 08:33 UTC, junu126 commented on poodle/src/container/common/HeaderContainer/HeaderContainer.tsx
> +    }));
redux hooks 사용할 때 custom hooks로 만들어서 한방에 return 시키면 좀 편해요.

https://github.com/makeToon/maketoon_front/blob/master/app/src/container/auth/index.ts

2020-04-05 08:33 UTC, junu126 commented on poodle/src/container/common/ModalContainer/ModalContainer.tsx
> +    const modalList = useMemo(() => [login, reset, yellowCheck, blueCheck, redError, warning], [login, reset, yellowCheck, blueCheck, redError, warning]);
useMemo를 왜 사용한건가용?

2020-04-05 08:33 UTC, junu126 commented on poodle/src/container/common/ModalContainer/ModalContainer.tsx
> +        <Modal modalClear={() => dispatch(modalClear())}>
FC에서 props로 함수를 내려줄 때 `useCallback`으로 함수를 새로 만들어서 내려주지 않으면..
성능 면에서 많이 떨어지게되요..

2020-04-05 08:33 UTC, junu126 commented on poodle/src/lib/utils/saga/createRequestSaga.ts
> +            yield delay(3000);
???

2020-04-05 08:33 UTC, junu126 commented on poodle/src/lib/utils/saga/createRequestSaga.ts
> +export default function createRequestSaga(type: any, request: any) {
return type 달아주세요

2020-04-05 08:33 UTC, junu126 commented on poodle/src/core/redux/sagas/header/index.ts
> +const loginSaga = createRequestSaga(LOGIN, () => ({ data: { userName: 'woochanleee' } }));
나중에 완성되면 다시 보겠습니다

2020-04-06 05:01 UTC, soheejang15 commented on poodle/src/components/common/Modal/RedErrorModal/RedErrorModal.tsx
> +            color='#ff6969'
자주 쓰이는 메인 컬러 코드 같은 건 상수로 미리 선언해서 쓰는 것도 좋을 것 같습니다

2020-04-07 08:30 UTC, woochanleee commented on package.json
> +{
이런 것들은 PR과정 없이 바로 하면 되군요! 알겠습니다!

2020-04-07 15:13 UTC, woochanleee commented on poodle/src/components/common/Header/Header.tsx
> +import * as S from '../../../styles/common/Header';
넵 검색후 적용해보겠습니다.

2020-04-07 15:22 UTC, woochanleee commented on poodle/src/components/common/Header/Header.tsx
> +                            <S.GNB onClick={logout}>{user.userName}</S.GNB>
GNB (Global Navication bar): 어느 페이지에 들어가든 공통적으로 사용할 수 있는 메뉴를 가리킨다. 
저도 몰랐는데 변수명 짓다가 마땅히 쓸게 없어서 발견했습니다!

2020-04-07 15:25 UTC, woochanleee commented
> 전체적으로 Type이 없는 곳이 많네영..
> 그리고 완성하지 못한 코드를 commit했는데 이러지 말고 다 완성 시키고 해주십셔

넵 아직 type을 확실히 정하지 않아서 그런부분이 생겼네요.. 
아!? PR할때는 완전 완성된 코드만 커밋해야 하군요! 새로 알았습니다. 브랜치에서 수정한 파일 모두 커밋해야하는줄 알았네요...

2020-04-07 15:38 UTC, woochanleee commented on poodle/src/components/common/Header/Header.tsx
> +function Header({ isLogin,  user, loginError, loginLoading, login, logout }: HeaderProps) {
넵 명시하겠습니다. 근데 FC를 쓴다면 기존 코드처럼
1. function Header({...): HeaderProps): FC { ... } 와
2. function Header({...)): FC<HeaderProps> { ... }
두가지 방법이 있는걸로 아는데 취향차이인가요?

2020-04-07 15:39 UTC, woochanleee commented on poodle/src/components/common/Modal/LoginModal/LoginModal.tsx
> +            <S.ETCSentence onClick={() => dispatch(modalOn(WARNINGMODAL))}>
앗 수정하겠습니다!

2020-04-07 15:58 UTC, junu126 commented on poodle/src/components/common/Header/Header.tsx
> +function Header({ isLogin,  user, loginError, loginLoading, login, logout }: HeaderProps) {
```
function Header({ ... }): FC<Props> { ... }
```

이렇게 하는것이 올바르겠습니다

2020-04-07 17:19 UTC, woochanleee commented on poodle/src/components/common/Header/Header.tsx
> +function Header({ isLogin,  user, loginError, loginLoading, login, logout }: HeaderProps) {
감사합니다!

2020-04-07 17:32 UTC, woochanleee commented on poodle/src/components/common/Header/Header.tsx
> +function Header({ isLogin,  user, loginError, loginLoading, login, logout }: HeaderProps) {
function 선언문에서는 알려주신방법대로 하니 오류가 나서 검색을 해봤는데,
다 화살표함수에서 사용하는 방식인 const App:FC<{}>() => { . . . } 이것 밖에 안나오더군요..
타입스크립트 문서에서 function MainButton(prop: SideProps): JSX.Element {...} 이런 방법이 있던데 이건 React에 사용하기 적합하지 않나요? (오류가 사라지긴 했습니다.)
그냥 앞으로 화살표함수로 사용하는게 나을까요..?

2020-04-07 17:34 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalContent.tsx
> +ModalContent.defaultProps = {
전에 공부하던 사이트에서 저런 방식을 본것 같아서 썼는데 안되는건가 보군요..! 수정하겠습니다

2020-04-07 17:36 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalContent.tsx
> +    const onClick = useCallback(() => {
애니메이션을 구현하기위해 테스트 차원에서 함수를 만들어 봤습니다..!
나중에 제대로 기능구현 하겠습니다.

2020-04-07 17:39 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalContent.tsx
> +const imageList: any = {
오호! enum을 이렇게 이용할수 있군요

2020-04-07 18:16 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalContent.tsx
> +const imageList: any = {
흠.. 어떻게 할지 감이 안잡히네요..
현재 설정해준 props값(ex/'BlueSuccess')에 따라 이걸 이용해 알맞은 이미지를 구별해야하는데,
enum같은 경우엔 [index]로 string이 들어갈수 없다하네요.. 약간의 힌트를 여쭙니다..

2020-04-07 18:22 UTC, woochanleee commented on poodle/src/components/common/Modal/ResetModal/ResetModal.tsx
> +    const pageList = [
넵 분리해서 깔끔히 다시 짜보겠습니다. type은 리턴타입 FC말씀하시는거죠? 이건 위쪽문제와 같이해결하겠습니다.

2020-04-07 18:24 UTC, woochanleee commented on poodle/src/container/common/HeaderContainer/HeaderContainer.tsx
> +    }));
아하! 참고하겠습니다. 가독성이 좋아지겠군요

2020-04-07 18:25 UTC, woochanleee commented on poodle/src/container/common/ModalContainer/ModalContainer.tsx
> +    const modalList = useMemo(() => [login, reset, yellowCheck, blueCheck, redError, warning], [login, reset, yellowCheck, blueCheck, redError, warning]);
음.. 모달 상태값이 바뀌면 다시 값을 할당해주기 위해서 했습니다. useMemo 없이도 잘 작동하는 부분인가요?

2020-04-07 18:26 UTC, woochanleee commented on poodle/src/container/common/ModalContainer/ModalContainer.tsx
> +        <Modal modalClear={() => dispatch(modalClear())}>
넵넵! 수정하겠습니다

2020-04-07 18:27 UTC, woochanleee commented on poodle/src/lib/utils/saga/createRequestSaga.ts
> +            yield delay(3000);
음.. delay부분은 로딩상태일때 로그인시도중... 이라는 메시지를 띄워보고 싶어서 잠깐 임의로 넣어봤습니다. 삭제하겠습니다..

2020-04-07 18:27 UTC, woochanleee commented on poodle/src/lib/utils/saga/createRequestSaga.ts
> +export default function createRequestSaga(type: any, request: any) {
네!!

2020-04-07 18:27 UTC, woochanleee commented on poodle/src/core/redux/sagas/header/index.ts
> +const loginSaga = createRequestSaga(LOGIN, () => ({ data: { userName: 'woochanleee' } }));
넵...

2020-04-07 18:28 UTC, woochanleee commented on poodle/src/components/common/Modal/RedErrorModal/RedErrorModal.tsx
> +            color='#ff6969'
네! 감사합니다!!

2020-04-08 01:06 UTC, junu126 commented on poodle/src/components/common/Header/Header.tsx
> +function Header({ isLogin,  user, loginError, loginLoading, login, logout }: HeaderProps) {
오우.. 저는 화살표 함수 동의합니다.

사실 저는 함수선언식으로 컴포넌트를 만들지를 않아서 타입을 저렇게 지정하면 오류날지 몰랐네요..

2020-04-08 01:07 UTC, junu126 commented on poodle/src/components/common/Modal/ModalContent.tsx
> +ModalContent.defaultProps = {
저거는 javascript로 컴포넌트 props를 명시할 때 사용합니다.

우리는 ts를 사용하니까 따로 명시할 이유가 없겠쥬?

2020-04-08 01:07 UTC, junu126 commented on poodle/src/components/common/Modal/ModalContent.tsx
> +    const onClick = useCallback(() => {
굿

2020-04-08 02:23 UTC, junu126 commented on poodle/src/components/common/Modal/ModalContent.tsx
> +const imageList: any = {
엥.. 상황 설명이 부족한 것 같습니다..

제가 말씀드린 `enum` 사용 방법은 상수 객체를 만드는 방법이었는데..

흐음 상황이 이해가 안가서.. 설명이 필요할 것 같네요.

2020-04-08 08:13 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalContent.tsx
> +const imageList: any = {
음.. 제 목적은 이미지 파일명을 props로 받아와서 그에 해당하는 이미지(import 해온 것들)를 
<img src={요기} /> 에 넣는것입니다.
근데 요기 에 props로 받아온것을 넣으면 그냥 string 형태로 들어가서 인식이 안되더라고요...
그래서 props를 key값으로 이미지(import해온것들)을 value로 놔서 객체를 하나 만들어서 해결했습니다. 이러한 문제점을 enum으로 상수 객체?를 만드는 방법으로 해결이 가능한가요??

2020-04-08 11:51 UTC, woochanleee commented on poodle/src/components/common/Header/Header.tsx
> +function Header({ isLogin,  user, loginError, loginLoading, login, logout }: HeaderProps) {
넵 화살표 함수로 전체 수정하겠습니다!

2020-04-09 08:16 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalContent.tsx
> +ModalContent.defaultProps = {
아하!? 그렇군요 "type"script를 쓰고있지용

2020-04-10 16:26 UTC, woochanleee commented
> 전체적으로 Type이 없는 곳이 많네영..
> 그리고 완성하지 못한 코드를 commit했는데 이러지 말고 다 완성 시키고 해주십셔

2020-04-11 07:32 UTC, junu126 requested changes

2020-04-11 07:32 UTC, junu126 commented on poodle/src/components/common/Modal/LoginModal/LoginModal.tsx
> +    const [loginInfo, setLoginInfo] = useState<{[key: string]: string}>({
타입을 줄 때 저렇게 주면 타입을 주는 의미가 없을 것 같아요.

```
interface loginInfoType {
    email: string;
    password: string
}
```

이런식으로 타입을 정적으로 타이핑 해주는 것이 좋을 것 같네요

2020-04-11 07:32 UTC, junu126 commented on poodle/src/components/common/Modal/ModalInput.tsx
> +    value: any,
typescript는 type을 달아야합니다.
anyscript가 아니올시다

2020-04-11 07:32 UTC, junu126 commented on poodle/src/components/common/Modal/ModalInput.tsx
> +const typeValue: any = {
typeValue 변수의 타입은
```
{
    email: string;
    password; string;
    verification: string;
}
```
이렇게 될 것 같네요

2020-04-11 12:41 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalInput.tsx
> +const typeValue: any = {
넵 any로 안하면 lint가 잡아서 그냥 input type에 따른 placeholder 를 설정해주는 코드를 없애고 placeholder를 props로 받아오게 수정했습니다.

2020-04-11 13:22 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalInput.tsx
> +    value: any,
넵 type 달았습니다. 기존에
`const [loginInfo, setLoginInfo] = useState({ ... })`
`const [resetInfo, setResetInfo] = useState({ ... })`
이렇게 두 state에 대해서 공통으로 사용했을경우 각각의 key가 달라 7번째줄의 value와 setValue가 any타입 아니고선 도저히 처리하는 방법을 몰라서 그냥 하나씩
`const [email, setEmail] = useState<string>('')`의 형태로 수정하였습니다...

2020-04-11 13:30 UTC, woochanleee commented on poodle/src/components/common/Modal/LoginModal/LoginModal.tsx
> +    const [loginInfo, setLoginInfo] = useState<{[key: string]: string}>({
넵 저렇게 준 이유가 loginInfo의 값들을 가지고 빈문자열과 공백을 포합하는지 찾기 위함이였는데 그 과정에서 

`Object.keys(loginInfo).map(key => loginInfo[key])`

이러한 코드를 짰더니 string 타입과 email | password 타입이 같지 않다고 하여 저런식으로 임시방편으로 해결한 거였습니다... 타입스크립트에서 객체의 값들을 조회할수 있는 다른 방법을 찾지 못해서 state의 구조를 수정하였습니다.

2020-04-12 05:57 UTC, junu126 approved these changes

2020-04-12 10:39 UTC, sema0710 approved these changes

2020-04-12 10:39 UTC, sema0710 commented on poodle/src/components/common/Modal/ModalBox.tsx
> +        <S.ModalBox onClick={(e: any) => e.stopPropagation()}>
e를 event type으로 지정하는 것이 좋지 않을까요?

2020-04-12 10:39 UTC, sema0710 commented on poodle/src/components/common/Modal/LoginModal/LoginModal.tsx
> +            <S.ETCSentence onClick={openModal(RESETMODAL)}>
이렇게 했을 때, 아마 제대로 작동 하지 않을 것 같은데....?
확인해주세요!

2020-04-12 10:57 UTC, woochanleee commented on poodle/src/components/common/Modal/LoginModal/LoginModal.tsx
> +            <S.ETCSentence onClick={openModal(RESETMODAL)}>
그쵸.. 저게 옛날 코드라 수정이 안되있는것 같네용 최신 커밋내용을 확인해보면 수정돼있습니다!

2020-04-12 10:57 UTC, woochanleee commented on poodle/src/components/common/Modal/ModalBox.tsx
> +        <S.ModalBox onClick={(e: any) => e.stopPropagation()}>
좋은 지적 감사합니다!

2020-04-12 11:06 UTC, merged