[CREATE] <mypage> components and styled
EntryDSM/poodle pull request #15
Opened 2020-05-06 13:47 UTC by woochanleee

# 제목을 적어주세요
마이페이지 컴포넌트를 제작했습니다.
## 목적
내 가입 정보를 확인하기 위하여
### 요약
컴포넌트 제작
요약 설명 (한두문장 이내)
스타일까지만 제작
### 상세
상세 설명
x
## 영향을 미치는 부분
x
간단히적어주세요
x
## 참조(선택)
x
연관된 이슈 번호들
x

2020-05-07 04:16 UTC, engolder commented on poodle/src/components/Mypage/Document/Document.tsx
> +export default Document;
```"files.eol": "auto"```
vscode에 설정있음

2020-05-07 04:45 UTC, engolder commented
@woochanleee 실행이 안되는뎁쇼

2020-05-07 04:49 UTC, woochanleee commented
> @woochanleee 실행이 안되는뎁쇼

아 이게 develop에 있던거에서 파생된 브랜치라 다른 친구가 짠 코드가 덜 포함되어있어서 아마 에러가 날꺼에요.. 그래서 전 그 부분 주석처리하고 개발한뒤 제가 짠 코드만 커밋하고 올렸어요..!

2020-05-07 04:52 UTC, engolder commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
이건 이렇게 할게아니라 확장의 개념으로 봐야함
MyInfoItem 이라는 컴포넌트가 DocumentLink컴포넌트가 들어갈 수 있는 공간을 마련해줘서 인터페이스를 열어줘야지
```tsx
<S.MyInfoBox>
  <S.MyInfoContent>
    ...
  </MyInfoContent>
  {props.someProp} // someProp: React.ReactNode
</S.MyInfoBox>
```
실행을 못시켜봐서 저부분이 어떤 역할인지 모름. 이름은 하나 정하고, 근데 아마 endAdornment 정도면 될것같음

2020-05-07 05:05 UTC, engolder requested changes

2020-05-07 05:05 UTC, engolder commented on poodle/src/components/Mypage/Mypage.tsx
> +                        ))
문제 1. enum을 배열처럼 사용하고있다.
문제 2. dummyData(나중엔 api data)와 MyInfoTitle 간 데이터 결합 순서가 단순 인덱스에 의존중.

1: array로 사용하는게 의도에 알맞아 보임 근데
2: 애초에 object.entires는 순서를 보장하지않고(이건 그냥 크롬구현방법이 정렬해서 주는것일 뿐, 이에대한 스펙은 없음) 보장한다고 하더라도 각 필드의 성격이 전혀 비슷하지 않기때문에 그냥 일일히 매핑해주는게 맞음

2번때문에 1번은 고칠필요가 없고 그냥 아예코드를 바꾸는게 좋을듯
```tsx
<MyInfoItem title="이름" infoValue={dummyData.name} />
<MyInfoItem title="성별" infoValue={dummyData.gender} />
...
```
이걸 좀더 이쁘게 바꾸려면
```tsx
[
  { label: "이름", value: dummyData.name },
  { label: "성별", value: dummyData.gender },
  ...
].map(({ label, value }) => <MyInfoItem title={label} infoValue={value} />)
...
```
식으로 가능

2020-05-07 05:05 UTC, engolder commented on poodle/src/components/Mypage/Mypage.tsx
> +                        ))
코드에서 중복을 줄인다고 항상 정답이 아니라는점

2020-05-07 05:05 UTC, engolder commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                    ))
마찬가지

2020-05-07 05:05 UTC, engolder commented on poodle/src/styles/Mypage/ProgressBar/index.ts
> +    background-image: url(${({ isfinished }) => isfinished === 'true' ? finishIcon : notFinishIcon});
styled-components에서 dynamic props는 사실 javascript style manipulate라 퍼포먼스 저하를 일으킴. 타이핑이 잡힌다는점에서는 좋지만 해당비용은 유저한테 청구하는거나 마찬가지라서
엔트리 서비스같은경우는 크게 최적화가 필요하진 않겠지만.. 이런부분에서 boolean prop을 받는것보다
class name으로 주는게 더 성능에는 이점이있음.
참고만 하세여 안바꿔도 크게 문제있는 코드는아니니까
```scss
background-image: ${notFinishIcon};
&.finished {
  background-image: ${finishIcon};
}
```

2020-05-07 05:08 UTC, engolder commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
사용할때는 이런식?
```tsx
<MyInfoBox title="최종제출" endAdornment={<S.DocumentLink to="/mypage/document">제출서류</S.DocumentLink>} />
```

2020-05-07 05:31 UTC, geni429 commented on poodle/src/components/Mypage/Mypage.tsx
> +const Mypage: React.FC<{}> = () => {
```suggestion
const Mypage: React.FC = () => {
```
props 가 없으면 제네릭 안넘겨도 됩니다.

2020-05-07 05:31 UTC, geni429 commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +    '전형구분': 'false',
```suggestion
    '전형구분': 'false',
```
value 가 boolean 이 아니라 string 으로 넘어오나요?

2020-05-07 05:31 UTC, geni429 commented on poodle/src/styles/Mypage/ProgressBar/index.ts
> +    export const Line = styled.hr`
```suggestion
export const Line = styled.hr`
```
Prettier 사용하시면 이런 이슈 줄일 수 있습니다.

2020-05-07 05:31 UTC, geni429 commented on poodle/src/styles/Mypage/SubmitDocument/index.ts
> +export { Wrapper as Wrapper };
```suggestion
```
export 가 필요한가요?

2020-05-07 05:31 UTC, geni429 commented on poodle/src/components/index.ts
> +export { Footer as Footer } from './default/Footer';
```suggestion
export { Footer } from './default/Footer';
```
assertion 안해줘도 될 것 같습니다.

2020-05-07 05:31 UTC, geni429 commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                            key={index}
```suggestion
                            key={data[0]}
```
index 값을 key 로 사용하는 건 의미가 없습니다.

2020-05-07 05:31 UTC, geni429 commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
endAdorment 너무 말이 어려운데.. suffixItem 어떤가요

2020-05-07 05:31 UTC, geni429 commented on poodle/src/components/Mypage/Mypage.tsx
> +                        ))
MyInfoItem 컴포넌트 props 를 수정하고 이렇게 사용할 수도 있음
```typescript
[
  { label: "이름", value: dummyData.name },
  { label: "성별", value: dummyData.gender },
  ...
].map(props => <MyInfoItem {...props} />)
...

2020-05-07 05:41 UTC, engolder commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
https://material-ui.com/api/input-base/#props
메테리얼에서 가져온 네이밍이고 item은 너무 일반적인 단어인것같은데요. 여러 의미를 가지고있음(인터페이스를 마주했을때 역할이 혼동될 여지가 있음)
adornment는 view에 그려질 엘리먼트를 의미한다는 뜻에서 적절하다고 생각합니다.
그리고 end랑 suffix는 둘다 뒤쪽을 의미하는데
둘다 general한 단어라서 뭘 사용해도 상관없다만 end가 더 짧아서 추천
네이밍과정은
의미가 적절한가 > 단어가 짧은가
순이라서 이렇게 추천했습니다(나름 선정기준이 있었다는 사실)

2020-05-07 05:43 UTC, engolder commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                            key={index}
(덧붙여서) 의미가 없다는말은 기본적으로 index를 사용한다는 뜻입니다 
https://reactjs.org/docs/lists-and-keys.html#keys
> If you choose not to assign an explicit key to list items then React will default to using indexes as keys

2020-05-07 05:48 UTC, geni429 commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
그렇다면 endNode 추천. (또는 suffixNode)
걍 뒤에 붙는 의미면 다 상관없음.

2020-05-07 05:49 UTC, geni429 commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
PR 작성자 맴

2020-05-07 05:57 UTC, engolder commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
node도 괜춘헌듯 문제없어보임

2020-05-08 03:24 UTC, woochanleee commented on poodle/src/components/Mypage/Document/Document.tsx
> +export default Document;
궁금증 1.
default settings로
`"files.eol": "auto"`
로 설정되어있는데 그래도 놔두면 될까요?
아니면 제 운영체제에 맞는 것으로 설정해야 할까요?
궁금증 2.
EOL에 알아보던 중 CRLF차이로 문제가 있다하여 아래와 같이 설정해주었는데 이러면 다음PR부터 적용이 되겠죠?(macOS사용중입니다.)
`git config --global core.eol native`
`git config --global core.autocrlf input`

2020-05-08 03:27 UTC, woochanleee commented on poodle/src/components/Mypage/Mypage.tsx
> +const Mypage: React.FC = () => {
음 suggestion으로 바로 커밋하니까 댓글을 다는게 사라져서 여기에 달아요.
Q. prop이 없으면 제네릭으로 안넘겨줘도 된다.
A. 아하? 그렇군요 쓸데 없는 코드였네요. 감사합니당

2020-05-08 03:29 UTC, woochanleee commented on poodle/src/components/Mypage/Mypage.tsx
> -const Mypage: React.FC<{}> = () => {
음 suggestion으로 바로 커밋하니까 댓글을 다는게 사라져서 여기에 달아요.
Q. prop이 없으면 제네릭으로 안넘겨줘도 된다.
A. 아하? 그렇군요 쓸데 없는 코드였네요. 감사합니당

2020-05-08 03:30 UTC, woochanleee commented on poodle/src/components/Mypage/Mypage.tsx
> +const Mypage: React.FC = () => {
음 suggestion으로 바로 커밋하니까 댓글을 다는게 사라져서 여기에 달아요.
Q. prop이 없으면 제네릭으로 안넘겨줘도 된다.
A. 아하? 그렇군요 쓸데 없는 코드였네요. 감사합니당

2020-05-08 04:34 UTC, woochanleee commented on poodle/src/components/Mypage/Mypage.tsx
> +                        ))
아하! Object.entries가 그렇게 작동하는지 몰랐네요. 코드를 저런 형태로 수정했습니다.
또, MyInfoItem 컴포넌트의 props를 수정해서 `{...props}`를 사용하는 방식도 적용했습니다.

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/components/Mypage/Mypage.tsx
> +                title === '최종제출' &&
일단 저
`<S.DocumentLink to="/mypage/document">제출서류</S.DocumentLink>`
는 사용자가 제출한 서류를 pdf로 미리보기할수 있는 페이지로 가는 링크입니다.
endAdornment props를 이용하여 컴포넌트가 들어갈수 있는 공간을 만들어주라는 방식을 이용해 수정했습니다.

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +    '전형구분': 'false',
api docs가 안나왔지만 99프로 boolean으로 올것 같네요.
![image](https://user-images.githubusercontent.com/48552260/81491175-df40cd00-92c5-11ea-801f-6cb2fabc18ff.png)
boolean형태로 styled components에 prop로 넘겨주니 사진과 같은 에러가 떠서 이를 해결하고자 string으로 코드를 짠것 같습니다.
이에 대해 구글링을 더 해보니 styled components는 props를 dom에 그대로 넘겨주고(?) dom 엘리먼트는 boolean속성을 가질수 없다해서 이를 어떻게 해결할지 고민하다가 
`<S.ProgressImageLink to={{ pathname: "전형구분", state: { isfinished: isfinished } }} />`라는 방식으로 수정해보았는데 더 나은 방법이 있나요? 잘 모르겠습니다...

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                            key={index}
우와? 그런 사실이 있엇군요.
key를 index말고 고유한 값으로 수정했습니다.

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                    ))
넵 그 방식대로 수정했습니다.

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/components/index.ts
> +export { Footer as Footer } from './default/Footer';
아? 그렇네요!
다음부턴 이렇게 안해야겠어요.

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/styles/Mypage/ProgressBar/index.ts
> +    background-image: url(${({ isfinished }) => isfinished === 'true' ? finishIcon : notFinishIcon});
오호! class를 쓰지않고 styled components만 써야한다는 고정관념에 빠져있엇네요.
성능에 이점이 있다니 수정할만한 메리트가 있는것 같습니다.
또, styled components에 props로 넘겨주면 그게 그대로 dom의 속성으로 가서 boolean 타입의 props를 어떻게 줘야할지 난감했엇는데 이렇게 class name으로 주니 깔끔하고 더 좋네요.

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/styles/Mypage/ProgressBar/index.ts
> +    export const Line = styled.hr`
오옹 prettier 맨날 적용이 안돼서 안썼는데 이번에 찾아보고 다시 해보니까 잘 작동하네요. 감사합니다.

2020-05-10 10:37 UTC, woochanleee commented on poodle/src/styles/Mypage/SubmitDocument/index.ts
> +export { Wrapper as Wrapper };
필요하지 않나요?? Document 컴포넌트에서 Wrapper를 사용하려고 저렇게 한건데 지우면 에러가 나요..
아니면 Document컴포넌트에서 직접 `@/styles/common`에 있는 Wrapper를 import해 사용하는 방법으로 하라는 건가요? (현재는 `@/styles/MypageDocument`에서 사용중입니다.)

2020-05-10 10:57 UTC, engolder approved these changes
비동기 데이터는 어떻게 관리할거??

2020-05-10 10:57 UTC, engolder commented on poodle/src/components/Mypage/Mypage.tsx
> +enum MyInfoTitle {
이제 이거 필요없을듯

2020-05-10 11:18 UTC, woochanleee commented
> 비동기 데이터는 어떻게 관리할거??

서버에서 주는데이터가 비동기 데이터죠??
그렇다면 이건 리덕스 사가로 관리할것입니다!

2020-05-10 11:21 UTC, woochanleee commented on poodle/src/components/Mypage/Mypage.tsx
> +enum MyInfoTitle {
아 그렇네용
삭제하겠습니다.

2020-05-11 06:27 UTC, junu126 commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +const ProgressItem: React.FC<{ label: string, isfinished: boolean, endAdornment?: React.ReactNode }> = ({ label, isfinished, endAdornment }) => {
라인이 너무 길어서 보기 불편한데 type을 따로 정의하는게 어떨까요?

2020-05-11 06:32 UTC, engolder commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                        { label: "자기소개서", isfinished: true },
확인안해봐서 모르겠는데 아마 기능이 아니라 스타일관련일거같음. 이건 javascript단에서 처리하기보단 css last-child혹은 last-of-type로 해결하는게 맞아보임

2020-05-11 06:35 UTC, engolder commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                        { label: "자기소개서", isfinished: true },
"데이터"와 "UI"를 구분지을 필요성이있음.
`label: "자기소개서"`인 아이템의 endAdorment가 undefined인 이유가 뭘까??
그건 자기소개서라서 그런게아니라 ui상에서 마지막에 위치해있기때문임.

2020-05-11 07:17 UTC, woochanleee commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +const ProgressItem: React.FC<{ label: string, isfinished: boolean, endAdornment?: React.ReactNode }> = ({ label, isfinished, endAdornment }) => {
앗 동의합니다.
생각없이 짯네요. 수정하겠습니다!

2020-05-11 07:17 UTC, woochanleee commented on poodle/src/components/Mypage/ProgressBar/ProgressBar.tsx
> +                        { label: "자기소개서", isfinished: true },
와..
'구분지을 필요성이 있다'는 말에 일침 맞았네요.
css last-of-type의로 `display: none;` 으로 수정했습니다.

2020-05-11 07:22 UTC, engolder approved these changes

2020-05-11 07:22 UTC, engolder commented
머지각~~~~~~~~~~~₩

2020-05-11 07:26 UTC, woochanleee commented
> 머지각~~~~~~~~~~~₩

각!!!!이지만 막혔..ㄷ..ㅏ 🚫

2020-05-11 13:03 UTC, junu126 approved these changes
머지각~~~~~🟢

2020-05-11 14:04 UTC, sema0710 approved these changes

2020-05-11 14:04 UTC, sema0710 approved these changes
컨플릭트만 해결하면 머지각~

2020-05-12 10:50 UTC, soheejang15 approved these changes

2020-05-30 13:23 UTC, junu126 approved these changes

2020-05-31 05:55 UTC, merged