pdf viewer
EntryDSM/poodle pull request #16
Opened 2020-06-03 04:04 UTC by sema0710

# pdf viewr
## 목적
학생들의 입학 서류를 pdf로 미리 보여주기 위함이다.
### 요약
pdf를 보여주는 부분의 마크업을 끝냄.
아직 server 구축이 되지 않아서 dummy_pdf를 넣어 놓음
### 상세
기능은 위의 요약을 따르고, 아직 더미 데이터를 넣어 놓았기 때문에,
디자인적인 요소만 봐주시면 감사하겠습니다.
## 영향을 미치는 부분
없습니다.
## 참조(선택)
없습니다.

2020-06-04 09:50 UTC, junu126 requested changes

2020-06-04 09:50 UTC, junu126 commented on poodle/src/components/Preview/PreviewFile.tsx
> +    const carculatePdfPage = useCallback(
🤔

2020-06-04 09:50 UTC, junu126 commented on poodle/src/components/Preview/pdf/PdfViewer.tsx
> +const PdfViewer: FC<Props> = ({
해당 컴포넌트는 완성이 안된건가?

2020-06-04 09:50 UTC, junu126 commented on poodle/src/components/Preview/pdf/PdfViewer.tsx
> +const PdfViewer: FC<Props> = ({
그리고 이번에 서버 통신을 pdf파일 자체를 띄우기로 했던가?

2020-06-04 13:49 UTC, sema0710 commented on poodle/src/components/Preview/PreviewFile.tsx
> +    const carculatePdfPage = useCallback(
앗 테스트 코드... 지우도록 하겠습니다

2020-06-04 13:50 UTC, sema0710 commented on poodle/src/components/Preview/pdf/PdfViewer.tsx
> +const PdfViewer: FC<Props> = ({
아직 얘기된 게 없어서 일시적으로 이렇게 만들어 놓았고 디자인 구성만 올렸었는데, 어....생겼네요 시정하겠습니다

2020-06-05 04:37 UTC, sema0710 commented on poodle/src/components/Preview/pdf/PdfViewer.tsx
> +const PdfViewer: FC<Props> = ({
요번에 용성이한테 물어보니 pdf 파일을 준다고 해서 그대로 진행하면 될 것 같습니다!

2020-06-05 04:38 UTC, sema0710 commented on poodle/src/components/Preview/PreviewFile.tsx
> +    const carculatePdfPage = useCallback(
예?

2020-06-08 02:11 UTC, soheejang15 approved these changes

2020-06-08 03:11 UTC, junu126 commented on poodle/src/components/Preview/pdf/PdfViewer.tsx
> +const PdfViewer: FC<Props> = ({
구웃

2020-06-08 03:11 UTC, junu126 approved these changes

2020-06-08 03:11 UTC, junu126 commented on poodle/src/components/Preview/PreviewFile.tsx
> +    const carculatePdfPage = useCallback(
볼때마다 느끼는건데 가독성이 너무 떨어져요 ㅠㅠㅠ

2020-06-08 03:17 UTC, woochanleee approved these changes
`<embed></embed>`태그라는 간단한 친구를 알려줬는데... 직접 구현하다니 대단해요👏

2020-06-08 03:56 UTC, sema0710 commented on poodle/src/components/Preview/PreviewFile.tsx
> +    const carculatePdfPage = useCallback(
그래서 iframe으로 수정되었습니다.

2020-06-08 03:57 UTC, merged