Feature/user info rows
EntryDSM/poodle pull request #18
Opened 2020-06-03 10:12 UTC by sema0710

# user_info rows
## 목적
사용자들이 정보를 입력하는 페이지를 등록하기 위해서
### 요약
사용자들의 정보를 입력하는 페이지의 각 줄들입니다.
### 상세
사용자들의 전화번호 같은 상세한 개인정보를 입력하는 input, radio등을 list로 감싸서 
디자인대로 만들어낸 줄들입니다.
## 영향을 미치는 부분
## 참조(선택)

2020-06-04 09:57 UTC, junu126 requested changes
중복코드 싸발적이고~

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserAddressRow.tsx
> +    const isEmptyCheck =
요론 함수는 util로 뺍시다

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserBirthDayRow.tsx
> +interface options {
enum으로 하는 것도 좋을 것 같슴니다

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserImg.tsx
> +                        <p>(JPG,JPEG,JPEG2000,PNG)</p>
이거 말고 다른거 넣으면 modal 띄우는거 알죠?

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserMiddleSchool.tsx
> +    const isEmptyCheck =
아까랑 동일

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserNameRow.tsx
> +    const isEmptyCheck =
요기도

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserNumberRow.tsx
> +    const [grade, gradeChange] = useState<Number>();
초기값을 지정해줍시다. `null`이나 0으로 할 수 있을 듯

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserNumberRow.tsx
> +    const isEmptyCheck =
요기도

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserPhoneNumRow.tsx
> +    const isEmptyCheck =
요기

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserProtectorPhoneNumRow.tsx
> +    const isEmptyCheck =
요기듀ㅗ

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserProtectorRow.tsx
> +    const isEmptyCheck =
아오

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/UserSchoolPhoneNumRow.tsx
> +    const isEmptyCheck =
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2020-06-04 09:57 UTC, junu126 commented on poodle/src/components/Info/RowType/constance/UserBirthDayConstance.ts
> +export const YEAR = [
요런거 for문 돌려서 만들 수 있을 것 같아요.

2020-06-04 13:51 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserAddressRow.tsx
> +    const isEmptyCheck =
확인했습니다! 리뷰 항상 감사합니다!

2020-06-04 13:51 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserImg.tsx
> +                        <p>(JPG,JPEG,JPEG2000,PNG)</p>
네네 모달 잠시 대기중입니다!

2020-06-04 13:51 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserMiddleSchool.tsx
> +    const isEmptyCheck =
아앗! 따로 빼겠습니당!!

2020-06-04 13:52 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserNumberRow.tsx
> +    const [grade, gradeChange] = useState<Number>();
아 까먹었던것 같네요 시정하겠습니다!!

2020-06-04 13:52 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserSchoolPhoneNumRow.tsx
> +    const isEmptyCheck =
저를 죽여주세오....

2020-06-04 13:53 UTC, sema0710 commented
죽여주세요...

2020-06-04 14:17 UTC, sema0710 commented
잘못했읍니다

2020-06-05 00:14 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserBirthDayRow.tsx
> +interface options {
constance 말씀하시는 건가요?

2020-06-05 00:15 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserProtectorRow.tsx
> +    const isEmptyCheck =
죄송합니다..
코드 중복 최대한 줄이도록 하겠습니다.

2020-06-05 04:47 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserImg.tsx
> +                        <p>(JPG,JPEG,JPEG2000,PNG)</p>
merge 후에 개발 할 예정입니다.

2020-06-05 04:47 UTC, sema0710 commented on poodle/src/components/Info/RowType/constance/UserBirthDayConstance.ts
> +export const YEAR = [
시도해 보겠습니다.

2020-06-08 03:49 UTC, junu126 commented on poodle/src/components/Info/RowType/constance/UserBirthDayConstance.ts
> +export const YEAR = [
굿

2020-06-08 03:50 UTC, junu126 approved these changes

2020-06-08 08:07 UTC, soheejang15 approved these changes

2020-06-08 10:41 UTC, merged