[CREATE] <join> components
EntryDSM/poodle pull request #2
Opened 2020-04-03 20:39 UTC by woochanleee

# 제목을 적어주세요
회원가입 컴포넌트를 만들었어요!
## 목적
회원가입을 하기 위하여..
### 요약
회원가입 페이지 제작
### 상세
회원가입을 하는 페이지를 만들었고  각 조건에 따른(ex, 인증코드 불일치 -> 경고문) 스타일을 구현해놨다.
## 영향을 미치는 부분
리덕스를 잘 연동해야 겠다.
## 참조(선택)
1. PULL_REQUEST_TEMPLATE.md 양식대로 작성하고 있는데 앞으로도 이런식으로 PR 하면 되나요?
2. 코드 변경수를 200줄로 하라 말씀해주셨는데 최소 기능만 개발했는데 400줄이 넘네요.. 특히 styled-components가 200줄을 차지해버리는데 어떡하죠..?
3. git flow? 관련 질문이 있는데 제가 앞서 [Header] 브랜치를 파서 PR을 했고 아직 머지가 안된 상황입니다. 근데 이번 [join] 브랜치를 파 개발할때 [Header] 브랜치에 있는 코드가 필요해 [Header] -> [join] 으로 머지 시킨후 개발을 했어요. 그랬더니 지금 [join] 브랜치를 PR날리려 하니 [develop] 브랜치에 없던 [Header] 브랜치의 코드가 [join]에 있다고 [Header] 코드들도 추가되었다고 판단해 "Showing  with 1,779 additions and 5 deletions."라는 어마어마한 양이 올라가게 생겼습니다. 이런 상황이 안생기려면 어떻게 해야 할까요?
현재 PR 할땐 [Header] -> [join] 으로 머지한 내용들을 삭제하고 날립니다!

2020-04-05 08:36 UTC, junu126 commented
1. 네 그렇게 하세영
2. branch를 더 나누세요. styling, redux conneting, view, 등 쪼갤 수 있잖아영
3. 그런상황이 오면 잘못 branch를 나눈거죠. branch를 더 잘게 쪼개면 상관 없을겁니다.

2020-04-05 08:39 UTC, junu126 requested changes

2020-04-05 08:39 UTC, junu126 commented on poodle/src/components/Join/Join.tsx
> +                        본 입학원서에 기재된 지원자의 개인정보는 신입생 입학관리업무의 원활한 수행을 위하여 개인정보의  수집‧유출‧오용‧남용으로부터 사생활의 비밀 등을 보호하도록 한{`\r\n`}
이런건 constanc 파일을 만들어서 관리해주세요.

정적 타이핑 같은건 코드에 추가시킬 필요없잖아요?

```
const AGREEMENT_1 = "본 입학원서 ~ ㅁㄴㅇㄹㅁㄴㅇ"
```
이런 느낌으로다가 따로 file만들어서 모읍시다

2020-04-05 08:39 UTC, junu126 commented on poodle/src/components/Join/JoinInput.tsx
> +JoinInput.defaultProps = {
??

2020-04-05 08:39 UTC, junu126 commented on poodle/src/styles/Join/index.ts
> +    background-image: url(${props => props.checked ? checked : check});
```
url(${props => props.checked ? checked : check});
```
이거 ES6를 이용해서
```
url(${({ checked })=> checked ? checked : check});
```
이거 가능

2020-04-09 08:51 UTC, woochanleee commented
> 1. 네 그렇게 하세영
> 2. branch를 더 나누세요. styling, redux conneting, view, 등 쪼갤 수 있잖아영
> 3. 그런상황이 오면 잘못 branch를 나눈거죠. branch를 더 잘게 쪼개면 상관 없을겁니다.

오호.. branch를 그렇게 나눌수 있군요.. 제가 어리석었습니다!!

2020-04-09 08:51 UTC, woochanleee commented on poodle/src/components/Join/JoinInput.tsx
> +JoinInput.defaultProps = {
띠용.. 삭제하겠습니다.

2020-04-09 09:41 UTC, woochanleee commented on poodle/src/components/Join/Join.tsx
> +                        본 입학원서에 기재된 지원자의 개인정보는 신입생 입학관리업무의 원활한 수행을 위하여 개인정보의  수집‧유출‧오용‧남용으로부터 사생활의 비밀 등을 보호하도록 한{`\r\n`}
넵! 적용했습니다!

2020-04-09 09:48 UTC, woochanleee commented on poodle/src/styles/Join/index.ts
> +    background-image: url(${props => props.checked ? checked : check});
checked 변수명이 중복되서 props를 이용한건데 변수명 바꿔서 es6로 수정했습니다!

2020-04-10 13:23 UTC, junu126 approved these changes

2020-04-12 10:38 UTC, sema0710 approved these changes

2020-04-12 11:11 UTC, merged