[CREATE] redux 연결 및 rows 합침
EntryDSM/poodle pull request #20
Opened 2020-06-03 10:16 UTC by sema0710

# user_info_page
## 목적
사용자 정보 입력 페이지를 등록하기 위해서
### 요약
rows들을 redux로 묶음과 동시에 페이지로 제작
### 상세
rows들을 redux로 묶음과 동시에 페이지로 제작
## 영향을 미치는 부분
## 참조(선택)

2020-06-04 09:58 UTC, junu126 requested changes

2020-06-04 09:58 UTC, junu126 commented on poodle/src/container/Info/Info.tsx
> +        <InfoDiv>
컴포넌트 분할이 필요할 것 같슴니다

2020-06-04 13:53 UTC, sema0710 commented on poodle/src/container/Info/Info.tsx
> +        <InfoDiv>
인정합니다.. 
시정하겠습니다!!

2020-06-08 03:50 UTC, junu126 approved these changes

2020-06-08 10:16 UTC, soheejang15 commented on poodle/src/components/default/common/Modal/SchoolSearchModal/SchoolSearchContent.tsx
> +        console.log("isClick")
필요없는 로그 지워주세영

2020-06-08 10:23 UTC, soheejang15 approved these changes

2020-06-08 10:23 UTC, soheejang15 commented on poodle/src/styles/common/Modal/index.ts
> +    color: #606060;
자주 보이는데 Global로 빼놓으면 편할 것 같아요

2020-06-08 10:23 UTC, soheejang15 commented on poodle/src/components/Info/Page/QualificationPage.tsx
> +        <>
여기 fragment 넣은 특별한 이유가 있나요? 지우는 걸 깜빡한건가 🤔

2020-06-08 10:38 UTC, sema0710 commented on poodle/src/components/default/common/Modal/SchoolSearchModal/SchoolSearchContent.tsx
> +        console.log("isClick")
아 확인했습니다!!

2020-06-08 10:39 UTC, sema0710 commented on poodle/src/components/Info/Page/QualificationPage.tsx
> +        <>
지우는걸 깜빡한 것 같네요.. 수정하겠습니다!

2020-06-09 01:07 UTC, sema0710 commented on poodle/src/styles/common/Modal/index.ts
> +    color: #606060;
앗! 그렇네요 감사합니다!

2020-06-09 01:07 UTC, merged