[CREATE] user_info_page actions들과 reducer
EntryDSM/poodle pull request #21
Opened 2020-06-03 10:19 UTC by sema0710

# 제목을 적어주세요
user_info_redux
## 목적
사용자 정보 입력 페이지를 등록하기 위함입니다.
### 요약
user_info page의 redux 의 action과 reducer 부분입니다.
### 상세
user_info_page의 redux의 action과 reducer를 정의하고 등록했습니다.
## 영향을 미치는 부분
간단히적어주세요
## 참조(선택)
연관된 이슈 번호들

2020-06-04 10:03 UTC, junu126 requested changes

2020-06-04 10:03 UTC, junu126 commented on poodle/src/core/redux/actions/Info/index.ts
> +export const NAME = "Info/NAME";
TS에서 
```ts
const NAME = "Info/NAME"
```
이라고 하면 나중에 객체에서 불러올 때 타입이 string으로 나옵니다.
```ts
const NAME = "Info/NAME" as const;
```
이런 식으로 작성하면 해결할 수 있습니다.

2020-06-04 10:03 UTC, junu126 commented on poodle/src/core/redux/actions/Info/index.ts
> +export const setName = (
parameter를 하나만 가져오지말고
```ts
export const setName = (payload: { name: string }) => ({ type: TYPE, payload });
```

이런식으로 객체로 받아오면 여러개의 데이터를 한번에 변경할 수 있지 않을까요?

2020-06-04 10:03 UTC, junu126 commented on poodle/src/core/redux/reducer/Info/index.ts
> +    picture: File,
```ts
picture: `File | null`
```

2020-06-04 10:03 UTC, junu126 commented on poodle/src/core/redux/reducer/Info/index.ts
> +    picture: new File([],"none.txt"),
```ts
picture: null,
```

2020-06-04 13:48 UTC, sema0710 commented on poodle/src/core/redux/reducer/Info/index.ts
> +    picture: File,
아..확인했습니다
수정하겠습니다

2020-06-04 13:48 UTC, sema0710 commented on poodle/src/core/redux/reducer/Info/index.ts
> +    picture: new File([],"none.txt"),
위에서 말씀하신대로 수정하겠습니다!!

2020-06-05 05:05 UTC, sema0710 commented on poodle/src/core/redux/actions/Info/index.ts
> +export const NAME = "Info/NAME";
아 그렇군요. 감사합니다!!

2020-06-08 03:51 UTC, junu126 approved these changes

2020-06-08 10:11 UTC, soheejang15 approved these changes

2020-06-08 10:38 UTC, merged