Feature/grade grade input
EntryDSM/poodle pull request #23
Opened 2020-06-03 10:44 UTC by sema0710

# grade_input
## 목적
학생들의 성적 입력 페이지에서 성적 입력 부분을 등록하기 위함입니다.
### 요약
학생들 성적 입력 페이지의 성적 입력부분을 만들었습니다.
### 상세
학생들 성적 입력 페이지의 성적 입력부분을 마크업 하고 디자인에 맞게 만들었습니다.
아직 redux는 연결하지 못했습니다.
## 영향을 미치는 부분
## 참조(선택)

2020-06-04 10:06 UTC, junu126 requested changes

2020-06-04 10:06 UTC, junu126 commented on poodle/src/components/Grade/GradeInput/Grade/GradeRow.tsx
> +            <GradeColumn onChange={()=>{}}/>
?

2020-06-04 10:06 UTC, junu126 commented on poodle/src/components/Grade/GradeInput/Grade/column/GradeColumn.tsx
> +                                    onClick={() => gradeClickHandler(grade)}
key가 없네요!

2020-06-04 13:47 UTC, sema0710 commented on poodle/src/components/Grade/GradeInput/Grade/column/GradeColumn.tsx
> +                                    onClick={() => gradeClickHandler(grade)}
아이고 key 없는 것 확인했습니다!!

2020-06-04 13:47 UTC, sema0710 commented on poodle/src/components/Grade/GradeInput/Grade/GradeRow.tsx
> +            <GradeColumn onChange={()=>{}}/>
보니 redux 연결이 안되어 있는 것 같네요
곧 수정하겠습니다

2020-06-05 04:02 UTC, sema0710 commented on poodle/src/components/Grade/GradeInput/Grade/GradeRow.tsx
> +            <GradeColumn onChange={()=>{}}/>
> ?

아직 redux 연결을 하지 않아서 일시적으로 넣어 놓았습니다.
pr 설명에 적어 두었습니다

2020-06-08 03:51 UTC, junu126 approved these changes

2020-06-08 10:09 UTC, soheejang15 approved these changes

2020-06-08 10:37 UTC, merged