[CREATE] 미이수 학기를 설정하는 부분의 markup
EntryDSM/poodle pull request #24
Opened 2020-06-03 10:49 UTC by sema0710

# 학생들 결석과 같은 미이수 입력 페이지 등록
## 목적
학생들이 미이수에 관련된 정보를 입력하는 페이지를 등록하기 위함이다.
### 요약
학생들의 결석, 결과, 지각과 같은 정보를 입력하는 페이지를 마크업하고
redux에 연결했습니다.
### 상세
학생들의 결석, 결과, 지각, 조퇴 같은 정보를 입력하는 페이지를 마크업하고
redux에 연결했습니다.
## 영향을 미치는 부분
## 참조(선택)

2020-06-04 10:06 UTC, junu126 requested changes

2020-06-04 10:06 UTC, junu126 commented on poodle/src/components/Grade/NonTransferSemester/column/SemesterColumn.tsx
> +                    onChange={()=>{}}
??

2020-06-04 13:46 UTC, sema0710 commented on poodle/src/components/Grade/NonTransferSemester/column/SemesterColumn.tsx
> +                    onChange={()=>{}}
오잉...? 확인 후 수정하겠습니다
제 예상으로는..파일이 롤백된것 같네요

2020-06-05 04:01 UTC, sema0710 commented on poodle/src/components/Grade/NonTransferSemester/column/SemesterColumn.tsx
> +                    onChange={()=>{}}
> ??

아 다시한번 생각해 보니까, 아직 redux 연결 안하고 디자인만 마크업 한거였습니다.
곧 redux 연결하겠습니다

2020-06-08 03:52 UTC, junu126 approved these changes

2020-06-08 10:03 UTC, soheejang15 approved these changes

2020-06-08 10:37 UTC, merged