헤더 api 연동
EntryDSM/poodle pull request #32
Opened 2020-06-25 11:31 UTC by woochanleee

# 제목을 적어주세요
header와 로그인 api 리덕스를 연동했습니다.
## 목적
헤더에서 토큰을 관리하기 위해서
### 요약
api와 로그인 모달과 헤더를 연결하였습니다.
요약 설명 (한두문장 이내)
### 상세
상세 설명
## 영향을 미치는 부분
원래 header 브랜친데 로그인과 헤더가 관련있어서 같이 올리는점 양해바랍니다.
## 참조(선택)
연관된 이슈 번호들

2020-06-25 11:32 UTC, woochanleee commented
엥? 이게 왜 +762 야, 죄송합니다. 리뷰어님들...

2020-06-27 02:16 UTC, sema0710 approved these changes

2020-07-03 10:01 UTC, junu126 requested changes

2020-07-03 10:01 UTC, junu126 commented on poodle/src/lib/api/client.ts
> +  baseURL: process.env.REACT_APP_API_URL,
default header로 `content-type: application/json`도 같이 너어줘도 될 것 같습니다.

2020-07-04 04:14 UTC, woochanleee commented on poodle/src/lib/api/client.ts
> +  baseURL: process.env.REACT_APP_API_URL,
오오!!! 수정했습니다!

2020-07-04 13:54 UTC, junu126 approved these changes

2020-07-05 02:23 UTC, merged