Feature/all state change action on container
EntryDSM/poodle pull request #33
Opened 2020-07-07 01:21 UTC by sema0710

# saga 추가 및 container에 saga 연결
## 목적
saga를 이용하여 서버와 연결하기 위함이다.
prettier 연결로 인해 코드 변경 줄이 뻥튀기 되었습니다... 그 점 양해 부탁드립니다.
### 요약
saga 제작 및 연결
### 상세
모든 페이지의 사가를 만들었고, 3개 페이지의 container에 연결하였다.
## 영향을 미치는 부분
## 참조(선택)

2020-07-08 08:16 UTC, soheejang15 commented on poodle/src/container/Grade/ConnectionGrade.ts
> +  isQualification: state.QualificattionState.isQualification,
오타있어영

2020-07-08 09:54 UTC, junu126 requested changes

2020-07-08 09:54 UTC, junu126 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +        const response = await setFunc(USERTYPE_URL, request);
`const response = await setFunc(USERTYPE_URL, request);`
to
`await setFunc(USERTYPE_URL, request);`

2020-07-08 09:54 UTC, junu126 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +        const response = await setFunc(USERTYPE_URL, request);
변수명 실화냐 `setFunc`

2020-07-08 09:54 UTC, junu126 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +  const getTypeAndSetState = async () => {
`userCallback` 어디갔누

2020-07-08 09:54 UTC, junu126 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +  const graduationStatusChangeHandler = useCallback((status: string) => {
status를 유니온으로 하십셔

2020-07-08 10:10 UTC, sema0710 commented on poodle/src/container/Grade/ConnectionGrade.ts
> +  isQualification: state.QualificattionState.isQualification,
와우...감사합니다 단어 계속 쓰던거라 오타 없을거라고 생각했는데 있었네요 ㅠㅜ

2020-07-08 10:11 UTC, sema0710 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +  const graduationStatusChangeHandler = useCallback((status: string) => {
인정합니다...변경하겠습니다.
값이 정해져있는 것들은 다 유니온 처리 하겠습니다.

2020-07-08 10:11 UTC, sema0710 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +  const getTypeAndSetState = async () => {
useCallback...까먹은 게 있었네요 처리하겠습니다

2020-07-08 10:12 UTC, sema0710 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +        const response = await setFunc(USERTYPE_URL, request);
변수명은 처리하겠습니다. response는 생각해보니 saga에서 처리를 하는 녀석이라 없애도 될 것 같습니다. 
감사합니다!

2020-07-08 10:16 UTC, sema0710 commented on poodle/src/container/Grade/ConnectionGrade.ts
> +  isQualification: state.QualificattionState.isQualification,
생각해보니 저게 틀렸으면...redux 코드도 다 틀렸겠군요...수정하겠습니다

2020-07-08 10:19 UTC, soheejang15 commented on poodle/src/container/Grade/ConnectionGrade.ts
> +  isQualification: state.QualificattionState.isQualification,
ㅋㅋㅋㅋㅋㅋㅋㅋ화이팅

2020-07-08 10:52 UTC, soheejang15 approved these changes

2020-07-08 10:52 UTC, soheejang15 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +      qualifacationExam,
또 찾았드ㅏ

2020-07-08 10:52 UTC, soheejang15 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +                describe="*졸업자의 경우 졸업연도를 선택해주세요"
. 찍어주세요 - 전PM

2020-07-08 11:15 UTC, sema0710 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +      qualifacationExam,
아앗...죄송합니다 수정하겠습니다

2020-07-08 11:16 UTC, sema0710 commented on poodle/src/container/ChoiceType/ChoiceType.tsx
> +                describe="*졸업자의 경우 졸업연도를 선택해주세요"
아 . 찍겠습니다 감사합니다

2020-07-09 06:28 UTC, junu126 approved these changes

2020-07-09 06:44 UTC, merged