[CREATE] server request function and request type
EntryDSM/poodle pull request #35
Opened 2020-07-07 01:28 UTC by sema0710

# server request function and request type
## 목적
서버 통신 시에 필요한 request를 날리는 함수들과 그 타입들을 사용하기 위해서
### 요약
요청 함수 정의 및 타입 정의
### 상세
불러오기와 작성에 관련된 서버에 요청을 보내는 함수 작성 및 타입 정의
카카오 api에서 정보 가져오는 함수 정의
아직 제출은 완성하지 않았습니다.
상세 설명
## 영향을 미치는 부분
## 참조(선택)

2020-07-08 09:58 UTC, junu126 requested changes

2020-07-08 09:58 UTC, junu126 commented on poodle/src/lib/api/ApplicationApplyApi.ts
> +export const errorTypeCheck = (error: any) => {
axios의 error체크를 위한 함수라면 error의 타입을 `AxiosError`로 합시다.

2020-07-08 09:58 UTC, junu126 commented on poodle/src/lib/api/kakao/index.ts
> +            Authorization: `KakaoAK 2c8f36e27e83eb36b73d5d4aea7a7068`,
?? env같은거 써서 가리세요

2020-07-08 10:12 UTC, sema0710 commented on poodle/src/lib/api/kakao/index.ts
> +            Authorization: `KakaoAK 2c8f36e27e83eb36b73d5d4aea7a7068`,
아 맞다...감사합니다!!

2020-07-08 12:45 UTC, woochanleee commented on poodle/src/lib/api/ApplicationApplyApi.ts
> +export const errorTypeCheck = (error: any) => {
저 같은 경우엔 `AxiosError`로 해주었엇는데 생각해보니
`error.response.status` 에러코드 값만 필요한것 같더라구요.
이걸로 통일하는게 어떨까요?
`
type ErrorType = {
  response: {
    code: Number
  }
}
`

2020-07-09 06:31 UTC, junu126 approved these changes

2020-07-09 06:45 UTC, woochanleee approved these changes

2020-07-09 06:48 UTC, merged