Feature/saga
EntryDSM/poodle pull request #36
Opened 2020-07-09 08:14 UTC by sema0710

# sagas
## 목적
모든 페이지에 사가를 추가하기 위함이다.
### 요약
모든 페이지 사가 추가
### 상세
grade, info, type, introduction, preview의 saga를 만들고 서버 요청까지 연결했다.
## 영향을 미치는 부분
없음
## 참조(선택)
없음

2020-07-10 02:48 UTC, woochanleee requested changes

2020-07-10 02:48 UTC, woochanleee commented on poodle/src/core/redux/sagas/index.ts
> +  ]);
잘 합쳐지길 기원합니다...

2020-07-10 02:48 UTC, woochanleee commented on poodle/src/core/redux/store/index.ts
> +const logger = createLogger();
이 미들웨어는 사용하고 안지우신건가요??
applyMiddleware에 적용이 안돼있네요!

2020-07-11 05:18 UTC, sema0710 commented on poodle/src/core/redux/sagas/index.ts
> +  ]);
기원합시다..

2020-07-11 05:18 UTC, sema0710 commented on poodle/src/core/redux/store/index.ts
> +const logger = createLogger();
앗..안지웠네요 지우겠습니다 감사합니다!!😄

2020-07-12 23:21 UTC, woochanleee approved these changes

2020-07-13 01:50 UTC, junu126 approved these changes

2020-07-13 06:48 UTC, soheejang15 approved these changes

2020-07-13 08:19 UTC, merged