[UPDATE] <Join> component
EntryDSM/poodle pull request #39
Opened 2020-07-09 14:20 UTC by woochanleee

# 제목을 적어주세요
Join 컴포넌트를 업데이트 하였습니다.
## 목적
api 연동을 하기 위함
### 요약
api response에 따라 회원가입 기능을 구현하였습니다.
요약 설명 (한두문장 이내)
### 상세
상세 설명
## 영향을 미치는 부분
컴포넌트 파일 하나가 500줄이 넘어서 죄송합니다...
간단히적어주세요
## 참조(선택)
연관된 이슈 번호들

2020-07-13 01:56 UTC, junu126 requested changes

2020-07-13 01:56 UTC, junu126 commented on poodle/src/components/Join/JoinInput.tsx
> +    if (setInputFocused)
`setInputFocused`는 setter function 아닌가요? 

if문으로 검사하는 이유가 있을까요?

2020-07-13 01:56 UTC, junu126 commented on poodle/src/components/Join/JoinInput.tsx
> +      maxLength={label === 'code' ? 5 : undefined}
`undefined`보단 `null`이 좋을 것 같습니다

2020-07-13 02:22 UTC, woochanleee commented on poodle/src/components/Join/JoinInput.tsx
> +    if (setInputFocused)
1. 맞습니다.
2. JoinInput.tsx 28번째 코드를 보면 `setInputFocused`함수는 props로 있을수도 없을수도 있습니다. 예를들어 Join.tsx에 494번째 코드를 보면 준 모습입니다.
또한, `setInputFocused`는 비밀번호와 비밀번호 확인의 input 포커스를 위한 state입니다. 따라서 이에 해당되었을때 함수로 전달된 값이 있다면 55번째 이후의 코드를 실행합니다.

이렇게 구현한 이유) 지금 구현된 방식이 이메일과 인증코드 input은 focus가 안된 상태여도 그것을 입력할 차례일때 focus 스타일이 적용됩니다.(나머진 입력 불가 상태) 하지만 비밀번호와 비밀번호 확인의 경우 만약 비밀번호가 옳바르게 입력되어 입력불가한 상태로 바꿔두면 사용자가 비밀번호 확인을 입력하였을때 틀렸거나 다르게 바꾸고 싶어 비밀번호를 수정하고 싶어할수 있다 생각하여 비밀번호와 비밀번호 확인은 동시에 입력가능한 상태로 해두었고, 이럴시에 두 input에 포커스가 되기 때문에 `setInputFocused`라는 함수를 이용하여 focus 됐을시에만 효과가 적용되도록 구현하였습니다.

제 설명이 부족할수 있습니다. 이해가 안되는부분은 적극 피드백 해주시면 감사하겠습니다!

2020-07-13 02:22 UTC, woochanleee commented on poodle/src/components/Join/JoinInput.tsx
> +      maxLength={label === 'code' ? 5 : undefined}
오호!? 수정하겠습니다.

2020-07-13 02:31 UTC, woochanleee commented on poodle/src/components/Join/JoinInput.tsx
> +    if (setInputFocused)
생각해보니 `inputFocused`의 존재 여부로 했어도 될것 같네요. 이걸 의도하신건가요 혹시..?

2020-07-13 23:45 UTC, junu126 approved these changes

2020-07-14 07:52 UTC, soheejang15 approved these changes

2020-07-14 08:19 UTC, merged