Feature/footer
EntryDSM/poodle pull request #4
Opened 2020-04-04 08:07 UTC by sema0710

# 제목을 적어주세요
Create Footer
## 목적
Footer를 사용하기 위해서
### 요약
design에 있는 Footer를 구현하였습니다.
### 상세
링크 주소를 입력하진 않았지만 View를 모두 구현하였습니다.
## 영향을 미치는 부분
없습니다.
## 참조(선택)
없습니다.

2020-04-05 08:43 UTC, junu126 requested changes

2020-04-05 08:43 UTC, junu126 commented on poodle/src/components/default/Footer/FooterImgLink.tsx
> +    const redirectToLink = (link: string) => {
이거 새 탭 열리게 해야해영

2020-04-05 08:43 UTC, junu126 commented on poodle/src/components/default/Footer/Footer.tsx
> +import React from 'react';
이거 그냥 개인적으로 airbnb의 lint구조를 사용하다보니까 거슬려서 그런데 ㅋㅋ

library에서 import해오는 걸 맨 위로하고 나머지를 아래다 하는건 어떨까요?
단순 의견입니다.

```
import React, { FC } from 'react';

import { facebook, github } from '../../../assets/Footer';
import { FooterImgLink, FooterLink } from '../Footer';
import { 
    FooterDiv,
    FooterText,
    FooterTitle, 
    FooterImgButtonDiv,
} from '../../../styles/Footer';
```
이런 느낌

그리고 FC 타입 지정 안했네연

2020-04-05 08:59 UTC, sema0710 commented on poodle/src/components/default/Footer/FooterImgLink.tsx
> +    const redirectToLink = (link: string) => {
앗! 확인했습니다

2020-04-05 09:01 UTC, sema0710 commented on poodle/src/components/default/Footer/Footer.tsx
> +import React from 'react';
음..FC 지정 안 한 이유가 props를 받아오는 것이 없어서 그랬는데, 
props 없을 때 FC를 어떻게 사용하지 생각하다가 넣지 않았는데
어떻게 할 수 있나요?

2020-04-05 12:45 UTC, junu126 commented on poodle/src/components/default/Footer/Footer.tsx
> +import React from 'react';
그냥 component에 타입 넣어주면 되는데

```
const Component: FC = () => { ... }
```

2020-04-05 12:46 UTC, junu126 requested changes
FC 붙이십셔!

2020-04-06 05:17 UTC, soheejang15 commented on poodle/src/components/default/Footer/Footer.tsx
> +                <FooterText margin="20">ⓒ 2019 Entry</FooterText>
여기도 잊지 말고 constant로 빼서 관리해주세요

2020-04-07 04:50 UTC, sema0710 commented on poodle/src/components/default/Footer/Footer.tsx
> +import React from 'react';
아? 저번에 FC<>로 해서 에러가 났었군요
시정하겠습니다..

2020-04-07 04:51 UTC, sema0710 commented on poodle/src/components/default/Footer/Footer.tsx
> +                <FooterText margin="20">ⓒ 2019 Entry</FooterText>
아! 감사합니다
수정하겠습니다.

2020-04-07 07:15 UTC, junu126 approved these changes

2020-04-08 10:28 UTC, soheejang15 approved these changes

2020-04-08 11:01 UTC, merged