Feature/error fix
EntryDSM/poodle pull request #45
Opened 2020-07-15 10:06 UTC by sema0710

# error fix
## 목적
console.log 삭제 및 자잘한 코드 에러 수정
### 요약
자잘한 코드 에러 삭제
### 상세
console.log 삭제, 네이밍 실수, 작은 코드 에러같은 것들을 묶어서 pr 날림
## 영향을 미치는 부분
없음
## 참조(선택)
연관된 이슈 번호들

2020-07-16 01:23 UTC, woochanleee requested changes

2020-07-16 01:23 UTC, woochanleee commented on poodle/src/container/Grade/Grade.tsx
> +      console.log(isEmptyCheck(serviceTime));
```suggestion
```
console.log 발견했습니다!

2020-07-16 01:23 UTC, woochanleee commented on poodle/src/container/Introduction/Introduction.tsx
> +    console.log(state);
여기도.. 일부러 남겨두신건가용?

2020-07-16 01:23 UTC, woochanleee commented on poodle/src/container/Introduction/Introduction.tsx
> +    // >(INTRODUCTION_URL);
주석은 나중에 쓰려고 남겨두신 거죠?

2020-07-16 01:23 UTC, woochanleee commented on poodle/src/container/Introduction/Introduction.tsx
> +    // );
여기도?!

2020-07-16 02:07 UTC, sema0710 commented on poodle/src/container/Introduction/Introduction.tsx
> +    // );
무언가 잘못되었습니다. 확인 후 다시 알려드리겠습니다

2020-07-16 02:08 UTC, sema0710 commented on poodle/src/container/Introduction/Introduction.tsx
> +    // );
아 이 주석은 서버 연결을 위한 녀석인데 잠시 지워놓은 녀석입니다

2020-07-16 02:08 UTC, sema0710 commented on poodle/src/container/Introduction/Introduction.tsx
> +    // >(INTRODUCTION_URL);
이녀석도 서버 연결을 위한 녀석인데 현재 더미 데이터로 되어 있어용

2020-07-16 02:08 UTC, sema0710 commented on poodle/src/container/Introduction/Introduction.tsx
> +    console.log(state);
이게 왜 살아있지...?

2020-07-16 02:10 UTC, sema0710 commented on poodle/src/container/Introduction/Introduction.tsx
> +    console.log(state);
삭제 시켜 버렸습니다 감사합니다~

2020-07-16 02:21 UTC, woochanleee approved these changes

2020-07-17 01:57 UTC, soheejang15 commented on poodle/src/container/Introduction/Introduction.tsx
> +    );
type을 any로 한 데에는 이유가 있나요?

2020-07-17 14:01 UTC, sema0710 commented on poodle/src/container/Introduction/Introduction.tsx
> +    );
음...실수 한 것 같습니다.
잡아주셔서 감사합니다 😄

2020-07-20 05:32 UTC, soheejang15 approved these changes

2020-07-20 07:10 UTC, merged