졸업일 및 검정고시 합격일 년월으로 수정 및 선생님 요구사항 처리
EntryDSM/poodle pull request #57
Opened 2020-08-09 10:29 UTC by sema0710

# 졸업일 및 검정고시 합격일 년월으로 수정 및 선생님 요구사항 처리
## 목적
선생님 요구사항 처리 및 전형 변경으로 인한 사항 처리
### 요약
졸업일 및 검정고시 합격일 년월으로 수정, 이에 관련된 saga, aciton, reducer 수정, dropdown 폰트 사이즈 수정 가능하게 변경
### 상세
졸업일 및 검정고시 합격일 년월으로 수정, 이에 관련된 saga, aciton, reducer 수정, dropdown 폰트 사이즈 수정 가능하게 변경
## 영향을 미치는 부분
없습니다
## 참조(선택)
x

2020-08-09 23:45 UTC, woochanleee approved these changes

2020-08-10 06:37 UTC, junu126 requested changes

2020-08-10 06:37 UTC, junu126 commented on poodle/src/components/Info/RowType/QualificationUserImg.tsx
> +    const acceptFileTypes: string[] = spliceAcceptFileTypeString(
`spliceAcceptFileTypeString` 함수에서 return type을 지정해주셈

2020-08-10 06:37 UTC, junu126 commented on poodle/src/components/Info/RowType/UserImg.tsx
> +    const acceptFileTypes: string[] = spliceAcceptFileTypeString(
이것두

2020-08-10 08:05 UTC, sema0710 commented on poodle/src/components/Info/RowType/QualificationUserImg.tsx
> +    const acceptFileTypes: string[] = spliceAcceptFileTypeString(
앗...함수 맨날 타입 까먹네요 수정하겠습니다.
항상 감사합니다!

2020-08-10 08:05 UTC, sema0710 commented on poodle/src/components/Info/RowType/UserImg.tsx
> +    const acceptFileTypes: string[] = spliceAcceptFileTypeString(
수정하겠습니다. 항상 감사합니다

2020-08-10 08:08 UTC, sema0710 commented on poodle/src/components/Info/RowType/QualificationUserImg.tsx
> +    const acceptFileTypes: string[] = spliceAcceptFileTypeString(
아 지정해 줬는데 그냥 string[]로 받아온 것 같네요 그럼 변수 타입을 없앨까요?

2020-08-10 08:10 UTC, junu126 commented on poodle/src/components/Info/RowType/QualificationUserImg.tsx
> +    const acceptFileTypes: string[] = spliceAcceptFileTypeString(
넹

2020-08-10 12:22 UTC, sema0710 commented on poodle/src/components/Info/RowType/QualificationUserImg.tsx
> +    const acceptFileTypes: string[] = spliceAcceptFileTypeString(
> 넹

변경했습니다!!

2020-08-12 05:25 UTC, soheejang15 approved these changes

2020-08-12 07:51 UTC, junu126 approved these changes

2020-08-12 07:54 UTC, merged