Feature/default element
EntryDSM/poodle pull request #6
Opened 2020-04-09 14:37 UTC by sema0710

# 기본적인 요소들
## 사용되는 input 같은 기본적인 요소들을 merge 하는 것이 목적입니다.
### 요약
input, radio, checkbox 등을 제작하였습니다.
### 상세
input, radio, checkbox, title, button, pagenation, dropdown등을 제작하였고
input일 경우에는 그에 필요한 state 변경 함수를 연결 할 수 있게 했습니다.
아직 input은 미완성입니다(곧 수정됩니다.)
## 영향을 미치는 부분
이후에 생기는 모든 pr에 이 요소들을 조합한 page가 나올 것 입니다.
## 참조(선택)
없습니다.

2020-04-09 14:38 UTC, sema0710 commented
기본적인 요소를 만들다 보니 너무 많아졌네요.
616줄 죄송합니다 ㅠㅜ

2020-04-19 04:49 UTC, junu126 requested changes

2020-04-19 04:49 UTC, junu126 commented on poodle/src/components/default/ApplicationFormDefault/Dropdown/Dropdown.tsx
> +                                <DropdownElement onClick={()=> elementClickHandler(menuList,menu)}>
key넣어주세요

2020-04-19 04:49 UTC, junu126 commented on poodle/src/styles/ApplicationFormDefault/index.ts
> +    content: "";
content는 왜있는건가요?

2020-04-20 07:42 UTC, sema0710 commented on poodle/src/components/default/ApplicationFormDefault/Dropdown/Dropdown.tsx
> +                                <DropdownElement onClick={()=> elementClickHandler(menuList,menu)}>
앗....까먹었네요 확인했습니다.

2020-04-20 07:51 UTC, sema0710 commented on poodle/src/styles/ApplicationFormDefault/index.ts
> +    content: "";
죄송합니다..원래 적용하던 것과 겹쳐저서 남아 있는 것 같아요

2020-04-20 11:45 UTC, junu126 approved these changes

2020-04-22 15:04 UTC, soheejang15 approved these changes

2020-04-27 01:44 UTC, merged