학교 검색 모달 수정 및 세부사항 변경
EntryDSM/poodle pull request #64
Opened 2020-08-13 10:59 UTC by sema0710

# 학교 검색 모달 수정 및 세부사항 변경
## 목적
학교 검색 모달 수정 및 세부사항 변경을 머지하기 위해서
### 요약
학교 검색 모달 constance 로 빼고 검색 가능하게 만듬
page에 타입 추가
### 상세
학교 검색 모달 constance 로 빼고 검색 가능하게 만듬
page에 타입 추가, naming 수정, page router 수정
## 영향을 미치는 부분
간단히적어주세요
## 참조(선택)
연관된 이슈 번호들

2020-08-13 23:32 UTC, woochanleee requested changes

2020-08-13 23:32 UTC, woochanleee commented on poodle/src/App.tsx
>          <Route path='/Info' render={() => <ConnectInfo />} />
그런데 uri 첫글자를 대문자로 한 이유가 있나요??
통일하는게 좋을것 같아서용
그리고 `<Route render={ ... }/>` 렌더를 쓰신것도 궁금합니다!!!

2020-08-13 23:32 UTC, woochanleee commented on poodle/src/lib/utils/saga/createGetSaga.ts
> +        payload: { error },
이렇게 `{ }` 중괄호로 한 이유가 있나용?

2020-08-13 23:32 UTC, woochanleee commented on poodle/src/lib/utils/saga/createMovePageSaga.ts
> +        payload: { error },
여기도

2020-08-13 23:32 UTC, woochanleee commented on poodle/src/lib/utils/saga/createMovePageSaga.ts
> +        payload: { error },
근데 이건 테스트용 가짜 서버 통신 에러 값 아닌가요??
`catch (response)` response로 받는데 그건 안쓰고 `error` 변수를 쓰셧는데 설명 부탁드립니다!

2020-08-13 23:32 UTC, woochanleee commented on poodle/src/lib/utils/saga/createSaveSaga.ts
>          payload: error,
여긴 또 그대로네유

2020-08-13 23:36 UTC, sema0710 commented on poodle/src/App.tsx
>          <Route path='/Info' render={() => <ConnectInfo />} />
앗...수정하겠습니다...
생각없이 한 것 같네요

2020-08-13 23:38 UTC, woochanleee commented on poodle/src/App.tsx
>          <Route path='/Info' render={() => <ConnectInfo />} />
이건 저희의 초반 통일이 안이루어졌네요...

2020-08-13 23:51 UTC, sema0710 commented on poodle/src/lib/utils/saga/createGetSaga.ts
> +        payload: { error },
그 이유는 제 action이....모두 중괄호 쳐서 처리를 했더라고요 
예를 들면 error action type은
```payload: { error: ErrorType }``` 이라서...이렇게 처리를 했읍니다

2020-08-13 23:52 UTC, sema0710 commented on poodle/src/App.tsx
>          <Route path='/Info' render={() => <ConnectInfo />} />
노노 이건 내가 왜 이랬는지 모르겠음 ㅎㅎ

2020-08-13 23:52 UTC, sema0710 commented on poodle/src/lib/utils/saga/createMovePageSaga.ts
> +        payload: { error },
요거슨 방금 토의를 통해 수정했습니다.

2020-08-13 23:52 UTC, sema0710 commented on poodle/src/lib/utils/saga/createSaveSaga.ts
>          payload: error,
여긴 에러나는 부분이라서 수정!

2020-08-15 12:27 UTC, junu126 approved these changes

2020-08-18 06:47 UTC, woochanleee approved these changes

2020-08-18 06:47 UTC, merged